Repository lunar-sway/minestuck, pull requests merged in 2022-10, with the labels that each got.

#381 Cassette texture error fix and added "far" cassette model
  src/main/resources/assets/minestuck/blockstates/cassette_player.json
  src/main/resources/assets/minestuck/models/block/cassette/cassette_far.json
  src/main/resources/assets/minestuck/models/block/cassette/cassette_model.json
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_13.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_blocks.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_cat.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_chirp.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_dance_stab.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_emissary.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_far.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_mall.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_mellohi.png
  src/main/resources/assets/minestuck/textures/block/cassette/cassette_retro_battle.png
Labels: bug

#382 Increasing tall end grass generation frequency
  src/main/java/com/mraof/minestuck/world/gen/feature/MSPlacedFeatures.java
Labels: enhancement

#384 Fixing strawberry stem rendering
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/ColorHandler.java
Labels: bug

#359 datapack generated starting modus
  src/main/generated/resources/data/minestuck/minestuck/config/starting_modus.json
  src/main/java/com/mraof/minestuck/MinestuckConfig.java
  src/main/java/com/mraof/minestuck/data/MinestuckData.java
  src/main/java/com/mraof/minestuck/data/MinestuckStartingModusProvider.java
  src/main/java/com/mraof/minestuck/player/PlayerData.java
  src/main/java/com/mraof/minestuck/util/StartingModusManager.java
Labels: enhancement

#386 Add infiniverse as a dependency for registering land dimensions
  build.gradle
  gradle.properties
  src/main/java/com/mraof/minestuck/world/DynamicDimensions.java
  src/main/resources/META-INF/mods.toml
Labels: enhancement

#395 Updating iron and gold ore loot
  src/main/generated/resources/data/minestuck/loot_tables/blocks/end_stone_iron_ore.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/pink_stone_gold_ore.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/red_sandstone_gold_ore.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/red_sandstone_iron_ore.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/sandstone_gold_ore.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/sandstone_iron_ore.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/shade_stone_gold_ore.json
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
Labels: bug

#388 Increasing land generation height
  src/main/java/com/mraof/minestuck/MinestuckConfig.java
  src/main/java/com/mraof/minestuck/entry/EntryProcess.java
  src/main/java/com/mraof/minestuck/world/GateHandler.java
  src/main/java/com/mraof/minestuck/world/biome/WorldGenBiomeSet.java
  src/main/java/com/mraof/minestuck/world/gen/LandGenSettings.java
  src/main/java/com/mraof/minestuck/world/gen/MSDensityFunctions.java
  src/main/java/com/mraof/minestuck/world/gen/feature/FloorCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSPlacedFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/OasisFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SmallLibraryFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SurfaceFossilsFeature.java
  src/main/java/com/mraof/minestuck/world/gen/structure/SmallRuinPiece.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/EndLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/FloraLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/ForestLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/FrostLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/FungiLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/HeatLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/RainLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/RainbowLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/RockLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/SandLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/SandstoneLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/ShadeLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/WoodLandType.java
  src/main/resources/data/minestuck/dimension_type/land.json
Labels: enhancement, priority

#397 Small tweaks to Rock lands and fixed flooding of all caves in Lands
  src/main/java/com/mraof/minestuck/world/gen/LandGenSettings.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/RockLandType.java
Labels: bug, enhancement
