Repository lunar-sway/minestuck, pull requests merged in 2023-12, with the labels that each got.

#534 Stopping milk from curing Creative Shock
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/effects/CreativeShockEffect.java
Labels: cleanup

#511 Consort dialogue addition
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entity/consort/ConsortDialogue.java
Labels: enhancement

#527 Remove some unused models and textures
  src/main/resources/assets/minestuck/blockstates/alchemiter_lower_rod.json
  src/main/resources/assets/minestuck/blockstates/alchemiter_upper_rod.json
  src/main/resources/assets/minestuck/blockstates/frost_stairs.json
  src/main/resources/assets/minestuck/blockstates/inverted_vein_corner.json
  src/main/resources/assets/minestuck/blockstates/pink_cobblestone.json
  src/main/resources/assets/minestuck/blockstates/polished_coarse_stone.json
  src/main/resources/assets/minestuck/blockstates/totem_lathe_bottom_corner.json
  src/main/resources/assets/minestuck/blockstates/totem_lathe_carver.json
  src/main/resources/assets/minestuck/blockstates/vein.json
  src/main/resources/assets/minestuck/blockstates/vein_corner.json
  src/main/resources/assets/minestuck/models/block/alchemiter_lower_rod.json
  src/main/resources/assets/minestuck/models/block/alchemiter_upper_rod.json
  src/main/resources/assets/minestuck/models/block/aspect_blood_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_breath_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_doom_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_heart_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_hope_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_life_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_light_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_mind_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_rage_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_space_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_time_log_bark.json
  src/main/resources/assets/minestuck/models/block/aspect_void_log_bark.json
  src/main/resources/assets/minestuck/models/block/inverted_vein_corner.json
  src/main/resources/assets/minestuck/models/block/machine_grist_widget.json
  src/main/resources/assets/minestuck/models/block/polished_coarse_stone.json
  src/main/resources/assets/minestuck/models/block/sassacrusher.json
  src/main/resources/assets/minestuck/models/block/totem_lathe_bottom_corner.json
  src/main/resources/assets/minestuck/models/block/totem_lathe_carver.json
  src/main/resources/assets/minestuck/models/block/totem_lathe_dowel_rod.json
  src/main/resources/assets/minestuck/models/block/totem_lathe_dowel_rod_carved.json
  src/main/resources/assets/minestuck/models/block/totem_lathe_rod_active.json
  src/main/resources/assets/minestuck/models/block/totem_lathe_wheel_active.json
  src/main/resources/assets/minestuck/models/block/upper_slab_pink_brick.json
  src/main/resources/assets/minestuck/models/block/vein.json
  src/main/resources/assets/minestuck/models/block/vein_corner.json
  src/main/resources/assets/minestuck/models/block/vine_oak_planks.json
  src/main/resources/assets/minestuck/models/item/inverted_vein_corner.json
  src/main/resources/assets/minestuck/models/item/jumper_block_extension.json
  src/main/resources/assets/minestuck/models/item/pink_cobblestone.json
  src/main/resources/assets/minestuck/models/item/platform_block.json
  src/main/resources/assets/minestuck/models/item/polished_coarse_stone.json
  src/main/resources/assets/minestuck/models/item/vein.json
  src/main/resources/assets/minestuck/models/item/vein_corner.json
  src/main/resources/assets/minestuck/textures/block/grist_widget_1.png
  src/main/resources/assets/minestuck/textures/block/grist_widget_2.png
  src/main/resources/assets/minestuck/textures/block/inverted_vein_corner.png
  src/main/resources/assets/minestuck/textures/block/inverted_vein_corner.png.mcmeta
  src/main/resources/assets/minestuck/textures/block/vein_corner.png
  src/main/resources/assets/minestuck/textures/block/vein_corner.png.mcmeta
  src/main/resources/assets/minestuck/textures/block/vein_side.png
  src/main/resources/assets/minestuck/textures/block/vein_side.png.mcmeta
  src/main/resources/assets/minestuck/textures/block/vein_top.png
  src/main/resources/assets/minestuck/textures/item/jumper_block_extension.png
  unused textures/black-tile.png
  unused textures/blender_juice_brain.json
  unused textures/eyes1-tile.png
  unused textures/saddle-tile.png
Labels: cleanup

#510 Sopor Slime Pies
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/recipes/combinations/sopor_slime_pie.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/sopor_slime_pie.json
  src/main/generated/resources/data/minestuck/tags/mob_effect/sopor_sickness_whitelist.json
  src/main/java/com/mraof/minestuck/data/MinestuckData.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MSEffectTagsProvider.java
  src/main/java/com/mraof/minestuck/effects/MSEffects.java
  src/main/java/com/mraof/minestuck/effects/SoporSicknessEffect.java
  src/main/java/com/mraof/minestuck/item/MSCreativeTabs.java
  src/main/java/com/mraof/minestuck/item/MSFoods.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/foods/SoporSlimeItem.java
  src/main/java/com/mraof/minestuck/util/MSTags.java
  src/main/resources/assets/minestuck/models/item/sopor_slime_pie.json
  src/main/resources/assets/minestuck/textures/item/sopor_slime_pie.png
  src/main/resources/assets/minestuck/textures/mob_effect/sopor_sickness.png
Labels: enhancement

#542 fix right-clicking with item outside athenium menu
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/inventory/AtheneumMenu.java
Labels: bug

#512 Land type extensions for worldgen features
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/util/PreservingOptionalFieldCodec.java
  src/main/java/com/mraof/minestuck/world/DynamicDimensions.java
  src/main/java/com/mraof/minestuck/world/GateHandler.java
  src/main/java/com/mraof/minestuck/world/biome/LandBiomeSetType.java
  src/main/java/com/mraof/minestuck/world/biome/LandBiomeType.java
  src/main/java/com/mraof/minestuck/world/biome/LandCustomBiomeSettings.java
  src/main/java/com/mraof/minestuck/world/gen/LandChunkGenerator.java
  src/main/java/com/mraof/minestuck/world/lands/LandBiomeGenBuilder.java
  src/main/java/com/mraof/minestuck/world/lands/LandBiomeGenVerifier.java
  src/main/java/com/mraof/minestuck/world/lands/LandTypeExtensions.java
Labels: enhancement

#506 Editmode locations with some code cleanup for editmode and computer programs
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/block/machine/ComputerBlock.java
  src/main/java/com/mraof/minestuck/blockentity/ComputerBlockEntity.java
  src/main/java/com/mraof/minestuck/client/gui/EditmodeSettingsScreen.java
  src/main/java/com/mraof/minestuck/client/gui/MinestuckScreen.java
  src/main/java/com/mraof/minestuck/client/gui/playerStats/GristCacheScreen.java
  src/main/java/com/mraof/minestuck/client/gui/playerStats/InventoryEditmodeScreen.java
  src/main/java/com/mraof/minestuck/client/gui/playerStats/PlayerStatsContainerScreen.java
  src/main/java/com/mraof/minestuck/client/gui/playerStats/PlayerStatsScreen.java
  src/main/java/com/mraof/minestuck/computer/ProgramData.java
  src/main/java/com/mraof/minestuck/computer/editmode/ClientDeployList.java
  src/main/java/com/mraof/minestuck/computer/editmode/ClientEditHandler.java
  src/main/java/com/mraof/minestuck/computer/editmode/ClientEditToolDrag.java
  src/main/java/com/mraof/minestuck/computer/editmode/ClientEditmodeData.java
  src/main/java/com/mraof/minestuck/computer/editmode/EditData.java
  src/main/java/com/mraof/minestuck/computer/editmode/EditmodeLocations.java
  src/main/java/com/mraof/minestuck/computer/editmode/ServerEditHandler.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entity/item/VitalityGelEntity.java
  src/main/java/com/mraof/minestuck/network/EditmodeTeleportPacket.java
  src/main/java/com/mraof/minestuck/network/MSPacketHandler.java
  src/main/java/com/mraof/minestuck/network/ServerEditPacket.java
  src/main/java/com/mraof/minestuck/network/data/EditmodeLocationsPacket.java
  src/main/java/com/mraof/minestuck/player/PlayerData.java
  src/main/java/com/mraof/minestuck/skaianet/SburbConnection.java
  src/main/java/com/mraof/minestuck/skaianet/SburbHandler.java
  src/main/java/com/mraof/minestuck/skaianet/SkaianetHandler.java
  src/main/resources/assets/minestuck/textures/gui/editmode/interact_multiple_mode.png
  src/main/resources/assets/minestuck/textures/gui/editmode/interact_single_mode.png
  src/main/resources/assets/minestuck/textures/gui/editmode/noclip_active.png
  src/main/resources/assets/minestuck/textures/gui/editmode/noclip_inactive.png
  src/main/resources/assets/minestuck/textures/gui/generic_extra_large.png
Labels: enhancement
