Repository lunar-sway/minestuck, pull requests merged in 2023-04, with the labels that each got.

#437 Skaianet Denier block
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/forge/tags/blocks/needs_wood_tool.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/generated/resources/data/minestuck/advancements/recipes/minestuck/skaianet_denier.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/skaianet_denier.json
  src/main/generated/resources/data/minestuck/recipes/skaianet_denier.json
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckRecipeProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/entry/EntryProcess.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/resources/assets/minestuck/blockstates/skaianet_denier.json
  src/main/resources/assets/minestuck/models/block/skaianet_denier.json
  src/main/resources/assets/minestuck/models/item/skaianet_denier.json
  src/main/resources/assets/minestuck/textures/block/skaianet_denier_side.png
  src/main/resources/assets/minestuck/textures/block/skaianet_denier_top.png
Labels: enhancement

#436 Giant cakes
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/large_cake.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/pink_frosted_top_large_cake.json
  src/main/generated/resources/data/minestuck/recipes/combinations/large_cake.json
  src/main/generated/resources/data/minestuck/recipes/combinations/pink_frosted_top_large_cake.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/large_cake.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/pink_frosted_top_large_cake.json
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/world/gen/feature/LargeCakeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSCFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSPlacedFeatures.java
  src/main/java/com/mraof/minestuck/world/lands/title/CakeLandType.java
  src/main/resources/assets/minestuck/blockstates/large_cake.json
  src/main/resources/assets/minestuck/blockstates/pink_frosted_top_large_cake.json
  src/main/resources/assets/minestuck/models/block/large_cake.json
  src/main/resources/assets/minestuck/models/block/pink_frosted_top_large_cake0.json
  src/main/resources/assets/minestuck/models/block/pink_frosted_top_large_cake1.json
  src/main/resources/assets/minestuck/models/item/large_cake.json
  src/main/resources/assets/minestuck/models/item/pink_frosted_top_large_cake.json
  src/main/resources/assets/minestuck/textures/block/large_cake.png
  src/main/resources/assets/minestuck/textures/block/pink_frosted_top_large_cake_side.png
  src/main/resources/assets/minestuck/textures/block/pink_frosted_top_large_cake_top0.png
  src/main/resources/assets/minestuck/textures/block/pink_frosted_top_large_cake_top1.png
  src/main/resources/data/minestuck/structures/large_cake_birthday0.nbt
  src/main/resources/data/minestuck/structures/large_cake_birthday1.nbt
  src/main/resources/data/minestuck/structures/large_cake_birthday2.nbt
  src/main/resources/data/minestuck/structures/large_cake_double_layer_round.nbt
  src/main/resources/data/minestuck/structures/large_cake_eaten.nbt
  src/main/resources/data/minestuck/structures/large_cake_round.nbt
  src/main/resources/data/minestuck/structures/large_cake_round_extra_large.nbt
Labels: enhancement

#352 Ground Slam and tweaks to animated attack framework
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entity/AttackingAnimatedEntity.java
  src/main/java/com/mraof/minestuck/entity/ai/MobAnimationPhaseGoal.java
  src/main/java/com/mraof/minestuck/entity/ai/attack/AnimatedAttackWhenInRangeGoal.java
  src/main/java/com/mraof/minestuck/entity/ai/attack/GroundSlamGoal.java
  src/main/java/com/mraof/minestuck/entity/animation/ActionCooldown.java
  src/main/java/com/mraof/minestuck/entity/underling/OgreEntity.java
  src/main/java/com/mraof/minestuck/util/MSSoundEvents.java
  src/main/resources/assets/minestuck/animations/entity/underlings/ogre.animation.json
  src/main/resources/assets/minestuck/sounds.json
  src/main/resources/assets/minestuck/sounds/mob/slam.ogg
  src/main/resources/assets/minestuck/sounds/mob/swoosh.ogg
Labels: enhancement, priority

#440 Cruxtruder sound effect and creative mode players stop using up cruxite
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/blockentity/machine/CruxtruderBlockEntity.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/util/MSSoundEvents.java
  src/main/resources/assets/minestuck/sounds.json
  src/main/resources/assets/minestuck/sounds/random/cruxtruder_dowel.ogg
Labels: enhancement

#441 Grist Collector block and additional block tooltips
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/forge/tags/blocks/needs_wood_tool.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/grist_collector.json
  src/main/generated/resources/data/minestuck/recipes/combinations/grist_collector.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/grist_collector.json
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/block/machine/GristCollectorBlock.java
  src/main/java/com/mraof/minestuck/blockentity/MSBlockEntityTypes.java
  src/main/java/com/mraof/minestuck/blockentity/machine/GristCollectorBlockEntity.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/item/IncompleteSburbCodeItem.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/ReadableSburbCodeItem.java
  src/main/java/com/mraof/minestuck/item/block/ExtraInfoBlockItem.java
  src/main/resources/assets/minestuck/blockstates/grist_collector.json
  src/main/resources/assets/minestuck/models/block/grist_collector.json
  src/main/resources/assets/minestuck/models/item/grist_collector.json
  src/main/resources/assets/minestuck/textures/block/grist_collector_front.png
  src/main/resources/assets/minestuck/textures/block/grist_collector_left_side.png
  src/main/resources/assets/minestuck/textures/block/grist_collector_side.png
  src/main/resources/assets/minestuck/textures/block/grist_collector_top.png
Labels: enhancement

#442 Land type lists and land type tags
  CHANGELOG.md
  src/main/generated/resources/data/minestuck/tags/minestuck/terrain_land_type/forest.json
  src/main/generated/resources/data/minestuck/tags/minestuck/terrain_land_type/rock.json
  src/main/generated/resources/data/minestuck/tags/minestuck/terrain_land_type/sand.json
  src/main/generated/resources/data/minestuck/tags/minestuck/terrain_land_type/sandstone.json
  src/main/generated/resources/data/minestuck/tags/minestuck/title_land_type/monsters.json
  src/main/java/com/mraof/minestuck/data/MinestuckData.java
  src/main/java/com/mraof/minestuck/data/tag/TerrainLandTypeTagsProvider.java
  src/main/java/com/mraof/minestuck/data/tag/TitleLandTypeTagsProvider.java
  src/main/java/com/mraof/minestuck/entity/consort/ConsortDialogue.java
  src/main/java/com/mraof/minestuck/item/loot/conditions/LandTypeLootCondition.java
  src/main/java/com/mraof/minestuck/player/EnumAspect.java
  src/main/java/com/mraof/minestuck/skaianet/Generator.java
  src/main/java/com/mraof/minestuck/skaianet/PredefineData.java
  src/main/java/com/mraof/minestuck/skaianet/SburbHandler.java
  src/main/java/com/mraof/minestuck/util/MSTags.java
  src/main/java/com/mraof/minestuck/world/lands/ILandType.java
  src/main/java/com/mraof/minestuck/world/lands/LandTypeConditions.java
  src/main/java/com/mraof/minestuck/world/lands/LandTypes.java
  src/main/java/com/mraof/minestuck/world/lands/gen/LandTypeGenerator.java
  src/main/java/com/mraof/minestuck/world/lands/gen/LandTypeSelection.java
  src/main/java/com/mraof/minestuck/world/lands/gen/LandTypeSelectionLoader.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/ForestLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/NullTerrainLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/RainLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/RockLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/SandLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/SandstoneLandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/TerrainLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/BucketsLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/CakeLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/ClockworkLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/FrogsLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/LightLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/MonstersLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/NullTitleLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/PulseLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/RabbitsLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/SilenceLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/ThoughtLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/ThunderLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/TitleLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/TowersLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/WindLandType.java
  src/main/resources/data/minestuck/minestuck/terrain_land_types.json
  src/main/resources/data/minestuck/minestuck/title_land_types.json
Labels: enhancement

#353 Fireball goal and basilisk tweaks
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entity/MSEntityTypes.java
  src/main/java/com/mraof/minestuck/entity/ai/attack/FireballShootGoal.java
  src/main/java/com/mraof/minestuck/entity/ai/attack/GroundSlamGoal.java
  src/main/java/com/mraof/minestuck/entity/animation/MobAnimation.java
  src/main/java/com/mraof/minestuck/entity/underling/BasiliskEntity.java
  src/main/java/com/mraof/minestuck/util/MSSoundEvents.java
  src/main/resources/assets/minestuck/animations/entity/underlings/basilisk.animation.json
  src/main/resources/assets/minestuck/sounds.json
  src/main/resources/assets/minestuck/sounds/mob/bite.ogg
Labels: enhancement

#444 Land gen tweaks
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/world/gen/LandGenSettings.java
  src/main/java/com/mraof/minestuck/world/gen/MSNoiseParameters.java
Labels: enhancement

#445 Structure nbt defined shadewood trees and Shade rough biome tweaks
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/world/gen/feature/MSCFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSPlacedFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/OrnateShadewoodTreeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/ShadewoodTree.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/ShadeLandType.java
  src/main/resources/data/minestuck/structures/ornate_shadewood_tree0.nbt
  src/main/resources/data/minestuck/structures/ornate_shadewood_tree1.nbt
  src/main/resources/data/minestuck/structures/ornate_shadewood_tree2.nbt
  src/main/resources/data/minestuck/structures/ornate_shadewood_tree3.nbt
Labels: enhancement

#451 Suspicious mycelium
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/forge/tags/blocks/needs_wood_tool.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/suspicious_chiseled_mycelium_bricks.json
  src/main/generated/resources/data/minestuck/recipes/combinations/suspicious_chiseled_mycelium_bricks_from_sushroom.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/suspicious_chiseled_mycelium_bricks.json
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/resources/assets/minestuck/blockstates/suspicious_chiseled_mycelium_bricks.json
  src/main/resources/assets/minestuck/models/block/suspicious_chiseled_mycelium_bricks.json
  src/main/resources/assets/minestuck/models/item/suspicious_chiseled_mycelium_bricks.json
  src/main/resources/assets/minestuck/textures/block/suspicious_chiseled_mycelium_bricks.png
Labels: enhancement

#447 Combat and spawn related Geckolib tweaks
  src/main/java/com/mraof/minestuck/entity/MSEntityTypes.java
  src/main/java/com/mraof/minestuck/entity/underling/ImpEntity.java
  src/main/java/com/mraof/minestuck/entity/underling/LichEntity.java
  src/main/java/com/mraof/minestuck/entity/underling/UnderlingEntity.java
  src/main/java/com/mraof/minestuck/skaianet/UnderlingController.java
Labels: enhancement

#452 Unused Weapon Implementation PR #3
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/recipes/combinations/maraschino_cherry_scythe.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/maraschino_cherry_scythe.json
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/resources/assets/minestuck/models/item/maraschino_cherry_scythe.json
  src/main/resources/assets/minestuck/textures/item/maraschino_cherry_scythe.png
Labels: enhancement

#435 computer gui improvements
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/block/machine/ComputerBlock.java
  src/main/java/com/mraof/minestuck/blockentity/ComputerBlockEntity.java
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/gui/ColorSelectorScreen.java
  src/main/java/com/mraof/minestuck/client/gui/ComputerScreen.java
  src/main/java/com/mraof/minestuck/computer/ButtonListProgram.java
  src/main/java/com/mraof/minestuck/computer/ComputerProgram.java
  src/main/java/com/mraof/minestuck/computer/DiskBurner.java
  src/main/java/com/mraof/minestuck/computer/ISburbComputer.java
  src/main/java/com/mraof/minestuck/computer/ProgramData.java
  src/main/java/com/mraof/minestuck/computer/SburbClient.java
  src/main/java/com/mraof/minestuck/computer/SburbServer.java
  src/main/java/com/mraof/minestuck/computer/SettingsApp.java
  src/main/java/com/mraof/minestuck/computer/Theme.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/network/MSPacketHandler.java
  src/main/java/com/mraof/minestuck/network/RGBColorSelectPacket.java
  src/main/java/com/mraof/minestuck/network/computer/ThemeSelectPacket.java
  src/main/java/com/mraof/minestuck/player/ClientPlayerData.java
  src/main/java/com/mraof/minestuck/skaianet/SkaianetHandler.java
  src/main/resources/assets/minestuck/textures/gui/bsod_message.png
  src/main/resources/assets/minestuck/textures/gui/color_selector.png
  src/main/resources/assets/minestuck/textures/gui/desktop_icon/disk_burner.png
  src/main/resources/assets/minestuck/textures/gui/desktop_icon/invalid.png
  src/main/resources/assets/minestuck/textures/gui/desktop_icon/sburb_client.png
  src/main/resources/assets/minestuck/textures/gui/desktop_icon/sburb_server.png
  src/main/resources/assets/minestuck/textures/gui/desktop_icon/settings.png
  src/main/resources/assets/minestuck/textures/gui/sburb.png
  src/main/resources/assets/minestuck/textures/gui/theme/cetus.png
  src/main/resources/assets/minestuck/textures/gui/theme/crocker.png
  src/main/resources/assets/minestuck/textures/gui/theme/default.png
  src/main/resources/assets/minestuck/textures/gui/theme/echidna.png
  src/main/resources/assets/minestuck/textures/gui/theme/hephaestus.png
  src/main/resources/assets/minestuck/textures/gui/theme/pesterchum.png
  src/main/resources/assets/minestuck/textures/gui/theme/trollian.png
  src/main/resources/assets/minestuck/textures/gui/theme/typheus.png
Labels: enhancement

#458 Editmode and atheneum fixes
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/computer/editmode/DeployList.java
  src/main/java/com/mraof/minestuck/computer/editmode/ServerEditHandler.java
Labels: bug, enhancement

#462 Gutter-bound grist toast fix
  src/main/java/com/mraof/minestuck/alchemy/GristHelper.java
  src/main/java/com/mraof/minestuck/client/gui/toasts/GristToast.java
  src/main/java/com/mraof/minestuck/player/GristCache.java
Labels: bug

#459 Minestuck Particles registry and transportalizer particle
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/blockentity/TransportalizerBlockEntity.java
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/particles/TransportalizerParticle.java
  src/main/java/com/mraof/minestuck/util/MSParticleType.java
  src/main/resources/assets/minestuck/particles/transportalizer.json
  src/main/resources/assets/minestuck/textures/particle/transportalizer_0.png
  src/main/resources/assets/minestuck/textures/particle/transportalizer_1.png
  src/main/resources/assets/minestuck/textures/particle/transportalizer_2.png
  src/main/resources/assets/minestuck/textures/particle/transportalizer_3.png
Labels: enhancement

#457 Client cache cleanup
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/alchemy/GristHelper.java
  src/main/java/com/mraof/minestuck/client/gui/MinestuckScreen.java
  src/main/java/com/mraof/minestuck/client/gui/toasts/GristToast.java
  src/main/java/com/mraof/minestuck/client/util/GuiUtil.java
  src/main/java/com/mraof/minestuck/computer/editmode/ClientEditHandler.java
  src/main/java/com/mraof/minestuck/computer/editmode/ClientEditToolDrag.java
  src/main/java/com/mraof/minestuck/computer/editmode/EditData.java
  src/main/java/com/mraof/minestuck/computer/editmode/ServerEditHandler.java
  src/main/java/com/mraof/minestuck/network/GristToastPacket.java
  src/main/java/com/mraof/minestuck/network/MSPacketHandler.java
  src/main/java/com/mraof/minestuck/network/data/EditmodeCacheLimitPacket.java
  src/main/java/com/mraof/minestuck/player/ClientPlayerData.java
  src/main/java/com/mraof/minestuck/player/Echeladder.java
  src/main/java/com/mraof/minestuck/player/GristCache.java
Labels: bug, priority

#463 Creating Title-Subtitle style Land Entry message
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/skaianet/SburbHandler.java
Labels: enhancement

#464 Cone-based hit detection for underlings
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/entity/ai/attack/AnimatedAttackWhenInRangeGoal.java
  src/main/java/com/mraof/minestuck/entity/ai/attack/FireballShootGoal.java
  src/main/java/com/mraof/minestuck/entity/ai/attack/GroundSlamGoal.java
  src/main/java/com/mraof/minestuck/entity/underling/BasiliskEntity.java
  src/main/java/com/mraof/minestuck/entity/underling/LichEntity.java
  src/main/java/com/mraof/minestuck/entity/underling/OgreEntity.java
Labels: enhancement

#460 Entry delay and effect
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/MinestuckConfig.java
  src/main/java/com/mraof/minestuck/client/EntryEffect.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entry/EntryProcess.java
  src/main/java/com/mraof/minestuck/entry/PostEntryTask.java
  src/main/java/com/mraof/minestuck/network/EntryEffectPackets.java
  src/main/java/com/mraof/minestuck/network/MSPacketHandler.java
  src/main/java/com/mraof/minestuck/skaianet/SburbHandler.java
Labels: priority

#476 Add Cinnamon Sword
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/recipes/combinations/cinnamon_sword.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/cinnamon_sword.json
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/resources/assets/minestuck/models/item/cinnamon_sword.json
  src/main/resources/assets/minestuck/textures/item/cinnamon_sword.png
Labels: enhancement
