Repository lunar-sway/minestuck, pull requests merged in 2024-02, with the labels that each got.

#556 Tree stump feature
  CHANGELOG.md
  src/main/generated/resources/data/minestuck/worldgen/configured_feature/tree_stump.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/tree/tree_stump.json
  src/main/java/com/mraof/minestuck/data/worldgen/MSConfiguredFeatureProvider.java
  src/main/java/com/mraof/minestuck/data/worldgen/MSPlacedFeatureProvider.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSCFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSPlacedFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/TreeStumpFeature.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/ForestLandType.java
  src/main/resources/data/minestuck/structures/tree_stump.nbt
Labels: enhancement

#557 Introduce TemplatePlacement as a helper object for template features
  src/main/java/com/mraof/minestuck/world/gen/feature/AbstractTemplateFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/CakePedestalFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/FloorCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/LargeCakeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/LargeCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SmallCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SurfaceFossilsFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/TemplatePlacement.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/OrnateShadewoodTreeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/TreeStumpFeature.java
Labels: cleanup

#558 Frog Ruins feature and edits to tree stump
  CHANGELOG.md
  src/main/generated/resources/data/minestuck/worldgen/configured_feature/frog_ruins.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/frog_ruins.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/tree/tree_stump.json
  src/main/java/com/mraof/minestuck/data/worldgen/MSConfiguredFeatureProvider.java
  src/main/java/com/mraof/minestuck/data/worldgen/MSPlacedFeatureProvider.java
  src/main/java/com/mraof/minestuck/world/gen/feature/FrogRuinFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSCFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSFeatures.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MSPlacedFeatures.java
  src/main/java/com/mraof/minestuck/world/lands/title/FrogsLandType.java
  src/main/resources/data/minestuck/structures/frog_ruins_0.nbt
  src/main/resources/data/minestuck/structures/frog_ruins_1.nbt
Labels: enhancement

#561 Fixing crouching for block pressure plates
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/block/redstone/BlockPressurePlateBlock.java
Labels: bug

#555 Customizable and Lockable Transportalizers
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/trans_portalizer.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/transportalizer.json
  src/main/java/com/mraof/minestuck/block/machine/TransportalizerBlock.java
  src/main/java/com/mraof/minestuck/blockentity/TransportalizerBlockEntity.java
  src/main/java/com/mraof/minestuck/client/gui/TransportalizerScreen.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/block/TransportalizerItem.java
  src/main/java/com/mraof/minestuck/network/MSPacketHandler.java
  src/main/java/com/mraof/minestuck/network/TransportalizerPacket.java
  src/main/java/com/mraof/minestuck/world/storage/TransportalizerSavedData.java
Labels: enhancement

#560 Prismarine armor remodel
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/client/model/armor/PrismarineArmorModel.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/armor/PrismarineArmorItem.java
  src/main/resources/assets/minestuck/animations/prismarine_armor.animation.json
  src/main/resources/assets/minestuck/geo/prismarine_armor.geo.json
  src/main/resources/assets/minestuck/textures/models/armor/prismarine_armor.png
Labels: enhancement

#559 Iron-lass Remodel
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/client/model/armor/IronLassArmorModel.java
  src/main/java/com/mraof/minestuck/item/armor/IronLassArmorItem.java
  src/main/resources/assets/minestuck/animations/iron_lass.animation.json
  src/main/resources/assets/minestuck/geo/iron_lass_armor.geo.json
  src/main/resources/assets/minestuck/textures/models/armor/iron_lass.png
  src/main/resources/assets/minestuck/textures/models/armor/iron_lass_layer_1.png
  src/main/resources/assets/minestuck/textures/models/armor/iron_lass_layer_2.png
Labels: enhancement

#567 Parameterizing renderers and using defaulted model class
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/model/entity/ConsortModel.java
  src/main/java/com/mraof/minestuck/client/model/entity/PawnModel.java
  src/main/java/com/mraof/minestuck/client/model/entity/RotatingHeadAnimatedModel.java
  src/main/java/com/mraof/minestuck/client/model/entity/UnderlingModel.java
  src/main/java/com/mraof/minestuck/client/renderer/entity/ConsortRenderer.java
  src/main/java/com/mraof/minestuck/client/renderer/entity/PawnRenderer.java
  src/main/java/com/mraof/minestuck/client/renderer/entity/UnderlingRenderer.java
Labels: cleanup

#541 Data driven computer Themes
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/cetus.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/crocker.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/default.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/echidna.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/hephaestus.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/joy.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/pesterchum.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/sburb_95.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/trollian.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/typheus.json
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/block/machine/ComputerBlock.java
  src/main/java/com/mraof/minestuck/blockentity/ComputerBlockEntity.java
  src/main/java/com/mraof/minestuck/client/gui/ComputerScreen.java
  src/main/java/com/mraof/minestuck/client/gui/ComputerThemeScreen.java
  src/main/java/com/mraof/minestuck/computer/ButtonListProgram.java
  src/main/java/com/mraof/minestuck/computer/ISburbComputer.java
  src/main/java/com/mraof/minestuck/computer/SettingsApp.java
  src/main/java/com/mraof/minestuck/computer/Theme.java
  src/main/java/com/mraof/minestuck/computer/theme/ComputerTheme.java
  src/main/java/com/mraof/minestuck/computer/theme/ComputerThemes.java
  src/main/java/com/mraof/minestuck/computer/theme/MSComputerThemes.java
  src/main/java/com/mraof/minestuck/data/ComputerThemeProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckData.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckLanguageProvider.java
  src/main/java/com/mraof/minestuck/network/computer/ThemeSelectPacket.java
Labels: enhancement
