Repository lunar-sway/minestuck, pull requests merged in 2024-04, with the labels that each got.

#590 Add dialogue commands for testing and reviewing dialogue
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/command/MSCommands.java
  src/main/java/com/mraof/minestuck/command/MSSuggestionProviders.java
  src/main/java/com/mraof/minestuck/command/ReviewDialogueCommand.java
  src/main/java/com/mraof/minestuck/command/SetDialogueCommand.java
  src/main/java/com/mraof/minestuck/command/argument/DialogueCategoryArgument.java
  src/main/java/com/mraof/minestuck/command/argument/MSArgumentTypes.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entity/dialogue/DialogueNodes.java
  src/main/java/com/mraof/minestuck/entity/dialogue/RandomlySelectableDialogue.java
Labels: enhancement

#591 Fix save format for effect in area effect block
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/blockentity/redstone/AreaEffectBlockEntity.java
Labels: bug, priority

#594 Helper functions for common crafting recipes
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_brick_slab.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_brick_stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_brick_wall.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_button.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_pressure_plate.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_slab.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/cruxite_wall.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/flowery_mossy_stone_brick_stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_cruxite_slab.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_cruxite_stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_cruxite_wall.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_lacquered_uncarved_slab.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_lacquered_uncarved_stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_treated_uncarved_slab.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_treated_uncarved_stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_uncarved_slab.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/polished_uncarved_stairs.json
  src/main/java/com/mraof/minestuck/data/AspectTreeBlocksData.java
  src/main/java/com/mraof/minestuck/data/MSBlockStateProvider.java
  src/main/java/com/mraof/minestuck/data/SkaiaBlocksData.java
  src/main/java/com/mraof/minestuck/data/recipe/CommonRecipes.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckRecipeProvider.java
Labels: cleanup

#598 Carapacian dialogue
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/constant_nakking.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/constant_thipping.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/dread_waiting.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/dreamer/explain_dreamers.1.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/dreamer/explain_dreamers.2.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/dreamer/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/enemy.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/forlorn.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/glub_glub.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/not_so_bad.1.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/not_so_bad.2.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/not_so_bad.3.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/not_so_bad.4.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/propaganda.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/rain_sleet_or_snow.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/bad_mood.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/barter.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/frequently.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/start.1.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/start.2.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/start.3.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/sword_barter/thanks.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/carapacian_soldier/too_quiet.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/constant_nakking.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/constant_thipping.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/dread_waiting.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/dreamer.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/enemy.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/forlorn.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/glub_glub.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/not_so_bad.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/propaganda.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/rain_sleet_or_snow.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/sword_barter.json
  src/main/generated/resources/data/minestuck/minestuck/selectable_dialogue/carapacian_soldier/too_quiet.json
  src/main/java/com/mraof/minestuck/data/MinestuckData.java
  src/main/java/com/mraof/minestuck/data/dialogue/CarapacianSoldierDialogue.java
  src/main/java/com/mraof/minestuck/entity/carapacian/EnumEntityKingdom.java
  src/main/java/com/mraof/minestuck/entity/carapacian/PawnEntity.java
  src/main/java/com/mraof/minestuck/entity/consort/EnumConsort.java
  src/main/java/com/mraof/minestuck/entity/dialogue/RandomlySelectableDialogue.java
  src/main/java/com/mraof/minestuck/entity/dialogue/Trigger.java
  src/main/java/com/mraof/minestuck/entity/dialogue/Triggers.java
  src/main/java/com/mraof/minestuck/entity/dialogue/condition/Condition.java
  src/main/java/com/mraof/minestuck/entity/dialogue/condition/Conditions.java
Labels: enhancement

#601 4/13 cake - Chocolatey Cake
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/blockstates/chocolatey_cake.json
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_slice1.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_slice2.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_slice3.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_slice4.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_slice5.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_slice6.json
  src/main/generated/resources/assets/minestuck/models/block/chocolatey_cake_uneaten.json
  src/main/generated/resources/assets/minestuck/models/item/chocolatey_cake.json
  src/main/generated/resources/data/minestuck/loot_tables/blocks/chocolatey_cake.json
  src/main/generated/resources/data/minestuck/loot_tables/chests/medium_basic/title/minestuck/cake.json
  src/main/generated/resources/data/minestuck/recipes/combinations/chocolatey_cake.json
  src/main/generated/resources/data/minestuck/recipes/grist_costs/chocolatey_cake.json
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/data/MSBlockStateProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSChestLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/item/MSCreativeTabs.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/world/gen/feature/CakeFeature.java
  src/main/resources/assets/minestuck/textures/block/chocolatey_cake_bottom.png
  src/main/resources/assets/minestuck/textures/block/chocolatey_cake_inner.png
  src/main/resources/assets/minestuck/textures/block/chocolatey_cake_side.png
  src/main/resources/assets/minestuck/textures/block/chocolatey_cake_top.png
  src/main/resources/assets/minestuck/textures/item/chocolatey_cake.png
Labels: enhancement

#603 Fix issue with /sburbconnection
  src/main/java/com/mraof/minestuck/command/SburbPredefineCommand.java
  src/main/java/com/mraof/minestuck/skaianet/SburbConnections.java
  src/main/java/com/mraof/minestuck/skaianet/SkaianetTests.java
Labels: bug, cleanup

#592 Avoid/catch problems setting up a StructureBlockRegistry
  src/main/generated/resources/data/minestuck/tags/minestuck/terrain_land_type/is_dangerous.json
  src/main/generated/resources/data/minestuck/tags/minestuck/terrain_land_type/is_fluid_important.json
  src/main/java/com/mraof/minestuck/data/tag/TerrainLandTypeTagsProvider.java
  src/main/java/com/mraof/minestuck/util/MSTags.java
  src/main/java/com/mraof/minestuck/world/gen/LandGenSettings.java
  src/main/java/com/mraof/minestuck/world/gen/structure/blocks/StructureBlockRegistry.java
  src/main/java/com/mraof/minestuck/world/lands/title/FrogsLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/PulseLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/RabbitsLandType.java
  src/main/java/com/mraof/minestuck/world/lands/title/ThoughtLandType.java
Labels: bug

#578 Cleanup and codecs for recipe interpreters
  CHANGELOG.md
  src/main/generated/resources/data/minestuck/minestuck/grist_cost_generation_recipes.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/CookingCostInterpreter.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/DefaultInterpreter.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/InterpreterSerializer.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/InterpreterSerializers.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/InterpreterTypes.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/RecipeGeneratedCostHandler.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/RecipeInterpreter.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/RecipeSource.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/recipe/SmithingInterpreter.java
  src/main/java/com/mraof/minestuck/data/GeneratedGristCostConfigProvider.java
Labels: cleanup

#611 Fix conflicting alchemy recipe for Prismarine Shard and Silicone Caulk Bucket
  CHANGELOG.md
  src/main/generated/resources/data/minestuck/recipes/combinations/caulk_bucket.json
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
Labels: bug
