Repository lunar-sway/minestuck, pull requests merged in 2024-01, with the labels that each got.

#544 MSBlocks Reorg
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
Labels: cleanup

#546 dispenser behaviours
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/item/BarbasolBombItem.java
  src/main/java/com/mraof/minestuck/item/ObsidianBucketItem.java
  src/main/java/com/mraof/minestuck/util/DispenserBehaviourUtil.java
Labels: enhancement

#538 Fixes and new content for Minestuck fluids
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/block/fluid/BlockFluidEnder.java
  src/main/java/com/mraof/minestuck/block/fluid/FlowingModFluidBlock.java
  src/main/java/com/mraof/minestuck/block/fluid/MSLiquidBlock.java
  src/main/java/com/mraof/minestuck/block/fluid/WaterColorsBlock.java
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/fluid/MSFluidType.java
  src/main/java/com/mraof/minestuck/fluid/MSFluids.java
  src/main/java/com/mraof/minestuck/util/MSCapabilities.java
  src/main/resources/assets/minestuck/textures/block/flowing_blood.png
  src/main/resources/assets/minestuck/textures/block/flowing_oil.png
  src/main/resources/assets/minestuck/textures/block/still_blood.png
  src/main/resources/assets/minestuck/textures/block/still_oil.png
Labels: bug, enhancement

#507 iron lass armor
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/model/armor/ArmorModels.java
  src/main/java/com/mraof/minestuck/client/particles/ExhaustParticle.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/armor/IronLassArmorItem.java
  src/main/java/com/mraof/minestuck/item/armor/MSArmorItem.java
  src/main/java/com/mraof/minestuck/util/MSParticleType.java
  src/main/java/com/mraof/minestuck/util/MSSoundEvents.java
  src/main/resources/assets/minestuck/particles/exhaust.json
  src/main/resources/assets/minestuck/sounds.json
  src/main/resources/assets/minestuck/sounds/item/jetpack_flight.ogg
  src/main/resources/assets/minestuck/textures/particle/exhaust_0.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_1.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_2.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_3.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_4.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_5.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_6.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_7.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_8.png
  src/main/resources/assets/minestuck/textures/particle/exhaust_9.png
Labels: enhancement

#549 Add mob spawn eggs
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/assets/minestuck/models/item/basilisk_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/dersite_bishop_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/dersite_pawn_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/dersite_rook_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/iguana_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/imp_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/lich_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/nakagator_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/ogre_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/prospitian_bishop_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/prospitian_pawn_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/prospitian_rook_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/salamander_spawn_egg.json
  src/main/generated/resources/assets/minestuck/models/item/turtle_spawn_egg.json
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckItemModelProvider.java
  src/main/java/com/mraof/minestuck/item/MSCreativeTabs.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/resources/assets/minestuck/textures/item/basilisk_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/dersite_bishop_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/dersite_pawn_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/dersite_rook_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/iguana_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/imp_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/lich_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/nakagator_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/ogre_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/prospitian_bishop_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/prospitian_pawn_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/prospitian_rook_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/salamander_spawn_egg.png
  src/main/resources/assets/minestuck/textures/item/turtle_spawn_egg.png
Labels: enhancement

#551 boat item code cleanup
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/entity/item/MetalBoatEntity.java
  src/main/java/com/mraof/minestuck/item/CustomBoatItem.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
Labels: bug, cleanup

#552 AspectTreeBlocks class
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/block/AspectTreeBlocks.java
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/data/MSBlockStateProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckRecipeProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/item/MSCreativeTabs.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
Labels: cleanup
