Repository lunar-sway/minestuck, pull requests merged in 2024-03, with the labels that each got.

#575 Sneaking Disables Trajectory Block
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/block/TrajectoryBlock.java
Labels: bug

#574 Aspect tree data class
  src/main/generated/resources/data/forge/tags/blocks/bookshelves.json
  src/main/generated/resources/data/minecraft/tags/blocks/climbable.json
  src/main/generated/resources/data/minecraft/tags/blocks/fence_gates.json
  src/main/generated/resources/data/minecraft/tags/blocks/fences.json
  src/main/generated/resources/data/minecraft/tags/blocks/leaves.json
  src/main/generated/resources/data/minecraft/tags/blocks/logs.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/axe.json
  src/main/generated/resources/data/minecraft/tags/blocks/planks.json
  src/main/generated/resources/data/minecraft/tags/blocks/pressure_plates.json
  src/main/generated/resources/data/minecraft/tags/blocks/saplings.json
  src/main/generated/resources/data/minecraft/tags/items/leaves.json
  src/main/generated/resources/data/minecraft/tags/items/logs.json
  src/main/generated/resources/data/minecraft/tags/items/planks.json
  src/main/generated/resources/data/minecraft/tags/items/saplings.json
  src/main/java/com/mraof/minestuck/block/AspectTreeBlocks.java
  src/main/java/com/mraof/minestuck/data/AspectTreeBlocksData.java
  src/main/java/com/mraof/minestuck/data/MSBlockStateProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckRecipeProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
Labels: cleanup

#570 Prevent oversized stacks when captchaloguing slots
  CHANGELOG.md
  src/main/java/com/mraof/minestuck/inventory/captchalogue/CaptchaDeckHandler.java
Labels: bug

#568 Fix fall damage for minestuck fluids
  CHANGELOG.md
  build.gradle
  src/main/java/com/mraof/minestuck/fluid/MSFluidType.java
  src/main/java/com/mraof/minestuck/mixin/LivingEntityMixin.java
  src/main/resources/mixins.minestuck.json
Labels: bug

#576 Land type structure hook
  src/main/generated/resources/data/minestuck/worldgen/structure_set/consort_village.json
  src/main/generated/resources/data/minestuck/worldgen/structure_set/imp_dungeon.json
  src/main/generated/resources/data/minestuck/worldgen/structure_set/small_ruin.json
  src/main/java/com/mraof/minestuck/data/worldgen/MSStructureSetProvider.java
  src/main/java/com/mraof/minestuck/world/DynamicDimensions.java
  src/main/java/com/mraof/minestuck/world/gen/LandChunkGenerator.java
  src/main/java/com/mraof/minestuck/world/lands/ILandType.java
  src/main/java/com/mraof/minestuck/world/lands/terrain/TerrainLandType.java
Labels: enhancement

#571 More Advancements
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/all_modi.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/big_one_mil.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/buy_out_shop.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/double_digits.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/first_step.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/french_fry.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/halfway_point.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/intellibeam.json
  src/main/generated/resources/data/minestuck/advancements/minestuck/legendary_weapon.json
  src/main/generated/resources/data/minestuck/tags/items/legendary.json
  src/main/java/com/mraof/minestuck/advancements/EcheladderTrigger.java
  src/main/java/com/mraof/minestuck/advancements/EventTrigger.java
  src/main/java/com/mraof/minestuck/advancements/IntellibeamLaserstationTrigger.java
  src/main/java/com/mraof/minestuck/advancements/MSCriteriaTriggers.java
  src/main/java/com/mraof/minestuck/blockentity/machine/IntellibeamLaserstationBlockEntity.java
  src/main/java/com/mraof/minestuck/command/RungCommand.java
  src/main/java/com/mraof/minestuck/data/MSAdvancementProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckItemTagsProvider.java
  src/main/java/com/mraof/minestuck/inventory/ConsortMerchantInventory.java
  src/main/java/com/mraof/minestuck/player/Echeladder.java
  src/main/java/com/mraof/minestuck/util/MSTags.java
Labels: enhancement

#577 New computer Themes and small visual changes to computers
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/astral_charts.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/lifdoff.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/lowas.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/minestuck.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/sburb_10.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/scourging_heat.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/skaianet_black.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/skaianet_green.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/skaianet_white.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/spirograph.json
  src/main/generated/resources/assets/minestuck/minestuck/computer_themes/tilldeath.json
  src/main/java/com/mraof/minestuck/computer/ButtonListProgram.java
  src/main/java/com/mraof/minestuck/computer/theme/MSComputerThemes.java
  src/main/java/com/mraof/minestuck/data/ComputerThemeProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/resources/assets/minestuck/textures/gui/theme/astral_charts.png
  src/main/resources/assets/minestuck/textures/gui/theme/crocker.png
  src/main/resources/assets/minestuck/textures/gui/theme/lifdoff.png
  src/main/resources/assets/minestuck/textures/gui/theme/lowas.png
  src/main/resources/assets/minestuck/textures/gui/theme/minestuck.png
  src/main/resources/assets/minestuck/textures/gui/theme/sburb_10.png
  src/main/resources/assets/minestuck/textures/gui/theme/scourging_heat.png
  src/main/resources/assets/minestuck/textures/gui/theme/skaianet_black.png
  src/main/resources/assets/minestuck/textures/gui/theme/skaianet_green.png
  src/main/resources/assets/minestuck/textures/gui/theme/skaianet_white.png
  src/main/resources/assets/minestuck/textures/gui/theme/spirograph.png
  src/main/resources/assets/minestuck/textures/gui/theme/tilldeath.png
Labels: enhancement

#562 TemplatePlacement uses and structure feature cleanup
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/bucket.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/cake_pedestal.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/frog_ruins.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/parcel_pyxis.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/rabbit_placement.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/small_rabbit_placement.json
  src/main/generated/resources/data/minestuck/worldgen/placed_feature/tree/tree_stump.json
  src/main/java/com/mraof/minestuck/data/worldgen/MSPlacedFeatureProvider.java
  src/main/java/com/mraof/minestuck/world/gen/feature/BrokenSwordFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/BucketFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/CakeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/CakePedestalFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/FloorCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/FrogRuinFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/LargeCakeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/LargeCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/MesaFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/ParcelPyxisFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/PillarFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/RabbitPlacementFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/RockSpikeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SmallCogFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SmallLibraryFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SmallPillarFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/StructureBlockRegistryProcessor.java
  src/main/java/com/mraof/minestuck/world/gen/feature/SurfaceFossilsFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/TemplatePlacement.java
  src/main/java/com/mraof/minestuck/world/gen/feature/TowerFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/OrnateShadewoodTreeFeature.java
  src/main/java/com/mraof/minestuck/world/gen/feature/tree/TreeStumpFeature.java
  src/main/java/com/mraof/minestuck/world/gen/structure/village/ConsortVillagePieces.java
  src/main/java/com/mraof/minestuck/world/lands/title/CakeLandType.java
Labels: cleanup

#579 Imp dungeon code cleanup
  src/main/java/com/mraof/minestuck/world/gen/structure/ImpDungeonPieces.java
Labels: cleanup

#581 Skaia blocks class and item-block registry helper
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/forge/tags/blocks/needs_wood_tool.json
  src/main/generated/resources/data/forge/tags/blocks/stained_glass.json
  src/main/generated/resources/data/minecraft/tags/blocks/impermeable.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/generated/resources/data/minecraft/tags/blocks/slabs.json
  src/main/generated/resources/data/minecraft/tags/blocks/stairs.json
  src/main/generated/resources/data/minecraft/tags/blocks/walls.json
  src/main/generated/resources/data/minecraft/tags/items/slabs.json
  src/main/generated/resources/data/minecraft/tags/items/stairs.json
  src/main/generated/resources/data/minestuck/advancements/recipes/building_blocks/black_chess_stairs_from_stonecutting.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/api/alchemy/recipe/combination/CombinationRecipeBuilder.java
  src/main/java/com/mraof/minestuck/block/ItemBlockPair.java
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/block/SkaiaBlocks.java
  src/main/java/com/mraof/minestuck/blockentity/MSBlockEntityTypes.java
  src/main/java/com/mraof/minestuck/blockentity/SkaiaPortalBlockEntity.java
  src/main/java/com/mraof/minestuck/data/MSBlockStateProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/MinestuckLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/SkaiaBlocksData.java
  src/main/java/com/mraof/minestuck/data/loot_table/MSBlockLootTables.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckCombinationsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckRecipeProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/data/worldgen/MSBiomeProvider.java
  src/main/java/com/mraof/minestuck/item/MSCreativeTabs.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/world/biome/SkaiaBiome.java
  src/main/java/com/mraof/minestuck/world/gen/MSSurfaceBuilders.java
  src/main/java/com/mraof/minestuck/world/gen/structure/castle/CastleRoomPiece.java
  src/main/java/com/mraof/minestuck/world/gen/structure/castle/CastleSolidPiece.java
  src/main/java/com/mraof/minestuck/world/gen/structure/castle/CastleStaircasePiece.java
  src/main/java/com/mraof/minestuck/world/gen/structure/castle/CastleStartPiece.java
  src/main/java/com/mraof/minestuck/world/gen/structure/castle/CastleWallPiece.java
Labels: cleanup

#587 Response messages and player message type
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/camel/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/denizen/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/fur_coat/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/hungry/finally.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/hungry/finally2.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/hungry/first_no.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/hungry/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/mushroom_pizza/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/rap_battle/after_rap.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/rap_battle/school_that_fool.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/rap_battle/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/consort/title_presence/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/shady_consort/peppy_offer/next.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/shady_consort/peppy_offer/start.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/shady_consort/shady_offer/next.json
  src/main/generated/resources/data/minestuck/minestuck/dialogue/shady_consort/shady_offer/start.json
  src/main/java/com/mraof/minestuck/data/dialogue/ConsortDialogue.java
  src/main/java/com/mraof/minestuck/data/dialogue/DialogueProvider.java
  src/main/java/com/mraof/minestuck/data/dialogue/ShadyConsortDialogue.java
  src/main/java/com/mraof/minestuck/entity/dialogue/Dialogue.java
  src/main/java/com/mraof/minestuck/entity/dialogue/DialogueComponent.java
Labels: enhancement
