Repository lunar-sway/minestuck, pull requests merged in 2025-03, with the labels that each got.

#649 Fix and remove smaller todo comments
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/minestuck/recipe/grist_costs/powder_snow_bucket.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/alchemy/recipe/generator/SourceGristCost.java
  src/main/java/com/mraof/minestuck/block/HorseClockBlock.java
  src/main/java/com/mraof/minestuck/block/HorseClockMultiblock.java
  src/main/java/com/mraof/minestuck/block/LotusTimeCapsuleBlock.java
  src/main/java/com/mraof/minestuck/block/LotusTimeCapsuleMultiblock.java
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/block/fluid/MSLiquidBlock.java
  src/main/java/com/mraof/minestuck/block/fluid/WaterColorsBlock.java
  src/main/java/com/mraof/minestuck/block/machine/AlchemiterBlock.java
  src/main/java/com/mraof/minestuck/block/machine/CruxtruderBlock.java
  src/main/java/com/mraof/minestuck/block/machine/MultiMachineBlock.java
  src/main/java/com/mraof/minestuck/block/machine/PunchDesignixBlock.java
  src/main/java/com/mraof/minestuck/block/machine/TotemLatheBlock.java
  src/main/java/com/mraof/minestuck/blockentity/SkaiaPortalBlockEntity.java
  src/main/java/com/mraof/minestuck/blockentity/machine/TotemLatheBlockEntity.java
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/util/ExtraTooltips.java
  src/main/java/com/mraof/minestuck/computer/SettingsApp.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/recipe/MinestuckGristCostsProvider.java
  src/main/java/com/mraof/minestuck/effects/SuspicionEffect.java
  src/main/java/com/mraof/minestuck/entity/dialogue/condition/Condition.java
  src/main/java/com/mraof/minestuck/event/ClientEventHandler.java
  src/main/java/com/mraof/minestuck/fluid/IMSFog.java
  src/main/java/com/mraof/minestuck/inventory/ConsortMerchantMenu.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/RazorBladeItem.java
  src/main/java/com/mraof/minestuck/item/weapon/MagicRangedRightClickEffect.java
  src/main/java/com/mraof/minestuck/player/ClientPlayerData.java
  src/main/java/com/mraof/minestuck/player/Echeladder.java
  src/main/java/com/mraof/minestuck/player/EnumAspect.java
  src/main/java/com/mraof/minestuck/player/EnumClass.java
  src/main/java/com/mraof/minestuck/player/Title.java
Labels: cleanup

#642 Editmode Keybind
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/computer/editmode/ClientEditmodeData.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
Labels: enhancement

#657 1.20.4 patches
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/generated/resources/data/forge/tags/blocks/needs_wood_tool.json
  src/main/generated/resources/data/minecraft/tags/blocks/doors.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/axe.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json
  src/main/generated/resources/data/minecraft/tags/blocks/mineable/shovel.json
  src/main/generated/resources/data/minecraft/tags/blocks/trapdoors.json
  src/main/generated/resources/data/minecraft/tags/blocks/wooden_doors.json
  src/main/generated/resources/data/minecraft/tags/blocks/wooden_trapdoors.json
  src/main/java/com/mraof/minestuck/block/AspectTreeBlocks.java
  src/main/java/com/mraof/minestuck/block/MSBlocks.java
  src/main/java/com/mraof/minestuck/block/SkaiaBlocks.java
  src/main/java/com/mraof/minestuck/client/gui/ColorSelectorScreen.java
  src/main/java/com/mraof/minestuck/command/GutterCommand.java
  src/main/java/com/mraof/minestuck/data/AspectTreeBlocksData.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/data/tag/MinestuckBlockTagsProvider.java
  src/main/java/com/mraof/minestuck/skaianet/client/SkaiaClient.java
  src/main/resources/assets/minestuck/models/block/alchemiter_totem_pad_totem.json
  src/main/resources/assets/minestuck/textures/block/shade_stone.png
Labels: bug, cleanup

#647 Computer program cleanup
  CHANGELOG.md
  src/main/generated/resources/assets/minestuck/lang/en_us.json
  src/main/java/com/mraof/minestuck/Minestuck.java
  src/main/java/com/mraof/minestuck/block/machine/ComputerBlock.java
  src/main/java/com/mraof/minestuck/blockentity/ComputerBlockEntity.java
  src/main/java/com/mraof/minestuck/client/ClientProxy.java
  src/main/java/com/mraof/minestuck/client/gui/ColorSelectorScreen.java
  src/main/java/com/mraof/minestuck/client/gui/MSScreenFactories.java
  src/main/java/com/mraof/minestuck/client/gui/computer/ButtonListHelper.java
  src/main/java/com/mraof/minestuck/client/gui/computer/ComputerScreen.java
  src/main/java/com/mraof/minestuck/client/gui/computer/ComputerThemeScreen.java
  src/main/java/com/mraof/minestuck/client/gui/computer/DiskBurnerGui.java
  src/main/java/com/mraof/minestuck/client/gui/computer/ProgramGui.java
  src/main/java/com/mraof/minestuck/client/gui/computer/SburbClientGui.java
  src/main/java/com/mraof/minestuck/client/gui/computer/SburbServerGui.java
  src/main/java/com/mraof/minestuck/client/gui/computer/SettingsAppGui.java
  src/main/java/com/mraof/minestuck/computer/ButtonListProgram.java
  src/main/java/com/mraof/minestuck/computer/ComputerProgram.java
  src/main/java/com/mraof/minestuck/computer/DiskBurner.java
  src/main/java/com/mraof/minestuck/computer/DiskBurnerData.java
  src/main/java/com/mraof/minestuck/computer/ISburbComputer.java
  src/main/java/com/mraof/minestuck/computer/ProgramData.java
  src/main/java/com/mraof/minestuck/computer/ProgramType.java
  src/main/java/com/mraof/minestuck/computer/ProgramTypes.java
  src/main/java/com/mraof/minestuck/computer/SburbClient.java
  src/main/java/com/mraof/minestuck/computer/SburbClientData.java
  src/main/java/com/mraof/minestuck/computer/SburbServer.java
  src/main/java/com/mraof/minestuck/computer/SburbServerData.java
  src/main/java/com/mraof/minestuck/computer/SettingsApp.java
  src/main/java/com/mraof/minestuck/computer/editmode/EditmodeLocations.java
  src/main/java/com/mraof/minestuck/data/MinestuckEnUsLanguageProvider.java
  src/main/java/com/mraof/minestuck/entry/EntryProcess.java
  src/main/java/com/mraof/minestuck/item/IncompleteSburbCodeItem.java
  src/main/java/com/mraof/minestuck/item/MSItems.java
  src/main/java/com/mraof/minestuck/item/ReadableSburbCodeItem.java
  src/main/java/com/mraof/minestuck/item/components/MSItemComponents.java
  src/main/java/com/mraof/minestuck/network/computer/BurnDiskPacket.java
  src/main/java/com/mraof/minestuck/network/computer/ClearMessagePacket.java
  src/main/java/com/mraof/minestuck/skaianet/ClientAccess.java
  src/main/java/com/mraof/minestuck/skaianet/ComputerInteractions.java
  src/main/java/com/mraof/minestuck/skaianet/ComputerWaitingList.java
  src/main/java/com/mraof/minestuck/skaianet/SburbConnections.java
  src/main/java/com/mraof/minestuck/skaianet/ServerAccess.java
  src/main/java/com/mraof/minestuck/skaianet/client/SkaiaClient.java
Labels: bug, cleanup

#658 Fix setting of builder-based weapon item properties
  src/main/java/com/mraof/minestuck/item/weapon/WeaponItem.java
Labels: bug
